### ISSUE TITLE
iOS Field App Improvements for EAO

### ISSUE THREAD

**Issue by bcdevex** [bcgov/field-inspection-app-ios#9]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-field-improvements-for-eao-project-information---collaboration-system--epic-">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-field-improvements-for-eao-project-information---collaboration-system--epic-">visit the opportunity page</a>. The opportunity closes on <b>Thursday, December 6, 2018</b>.</p>

**Comment by jillcarr** [comment]
Hi all, I'm the Product owner for the app, just wanted to clarify that the opportunity closes at 16:00 PST on Wednesday, December 5th - not the date stated in the issue generation above.

**Comment by jasmeet17** [comment]
@jillcarr What's the best way to present relevant experience? My teammate and I have applications on App Store. And most of those applications were for clients whose repos are private. Do you think showing our work through App store links will help?

Also a team of 2 developers can apply together?

**Comment by jleach** [comment]
@jasmeet17 Your welcome to show App Store links - those are useful for sure. However, we're really interested in the level of code quality you can produce. This will help us both ensure the proponent's success; if they demonstrate top notch code quality then we won't have any surprises in the pull request to complete the project :)

**Comment by mark-a-wilson** [comment]
Hi @jasmeet17. I'm with the BCDevExchange team who runs the bcdevexchange.org application. 

Yes, a team of two developers is allowed. (I can understand your confusion because the form does imply a single developer.)

In the proposal form, please enter info for the developer you would want to receive the payment (and company info if you want the payment made to a company). Then, in your proposal material, go ahead and present all the developers you're putting forward and their experience etc.

**Comment by jasmeet17** [comment]
@jleach @mark-a-wilson Thanks for quick reply. It helped.

**Comment by jleach** [comment]
@devonkirk You'll be working with someone from with the BCGov; if the stars alight it'll probable be me.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by jasmeet17** [comment]
@jleach @mark-a-wilson 
hey guys
I just saw the opportunity has been assigned to some one. I was quite confident that I will get this opportunity. Can you guys share some feedback regarding our proposal? It will help me and my team to do better when applying for job at bcdev exchange next time

Thanks

**Comment by jleach** [comment]
@jasmeet17 Sent via email.
